# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build Issue Bot"

on:
  pull_request:
    paths:
      - 'issue-bot/**'
      - '.github/workflows/build-issue-bot.yml'
  push:
    branches:
      - "2.1.x"
    paths:
      - 'issue-bot/**'
      - '.github/workflows/build-issue-bot.yml'

concurrency:
  group: build-issue-bot-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  build-issue-bot:
    name: "Build Issue Bot"

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        script:
          - "../bin/phpstan"
          - "vendor/bin/phpunit"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.5"

      - uses: "ramsey/composer-install@v3"

      - name: "Install issue-bot dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          working-directory: "issue-bot"

      - name: "Tests"
        working-directory: "issue-bot"
        run: ${{ matrix.script }}
