# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Tests"

on:
  pull_request:
    paths-ignore:
      - 'compiler/**'
      - 'apigen/**'
      - 'changelog-generator/**'
      - 'issue-bot/**'
  push:
    branches:
      - "2.1.x"
    paths-ignore:
      - 'compiler/**'
      - 'apigen/**'
      - 'changelog-generator/**'
      - 'issue-bot/**'

concurrency:
  group: tests-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        operating-system: [ ubuntu-latest, windows-latest ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ds,mbstring
          ini-file: development
          ini-values: memory_limit=2G

      - uses: "ramsey/composer-install@v3"

      - name: "Tests"
        run: "make tests"

  tests-integration:
    name: "Integration tests"
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.2"
          tools: pecl
          extensions: ds,mbstring
          ini-file: development
          ini-values: memory_limit=1G

      - uses: "ramsey/composer-install@v3"

      - name: "Tests"
        run: "make tests-integration"

  tests-levels-matrix:
    name: "Determine levels tests matrix"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
          tools: pecl
          extensions: ds,mbstring
          ini-file: development
          ini-values: memory_limit=1G

      - uses: "ramsey/composer-install@v3"

      - id: set-matrix
        run: echo "matrix=$(php .github/workflows/tests-levels-matrix.php)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  tests-levels:
    needs: tests-levels-matrix

    name: "Levels tests"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        script: "${{fromJson(needs.tests-levels-matrix.outputs.matrix)}}"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
          tools: pecl
          extensions: ds,mbstring
          ini-file: development
          ini-values: memory_limit=1G

      - uses: "ramsey/composer-install@v3"

      - name: "Tests"
        run: "${{ matrix.script }}"

  tests-with-old-phpunit:
    name: "Tests with old PHPUnit"
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        operating-system: [ ubuntu-latest, windows-latest ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ds,mbstring
          ini-file: development
          ini-values: memory_limit=2G

      - name: "Downgrade PHPUnit"
        shell: bash
        run: "composer require --dev phpunit/phpunit:^9.6 sebastian/diff:^4.0 --update-with-dependencies --ignore-platform-reqs"

      - uses: "ramsey/composer-install@v3"

      - name: "Downgrade PHPUnit with Paratest"
        shell: bash
        run: "composer require --dev phpunit/phpunit:^9.6 brianium/paratest:^6.5 symfony/console:^5.4 symfony/process:^5.4 --update-with-dependencies --ignore-platform-reqs --working-dir=tests"

      - name: "Change to simple-downgrade PHP version"
        if: matrix.php-version == '7.4' || matrix.php-version == '8.0' || matrix.php-version == '8.1'
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.4"
          tools: pecl
          extensions: ds,mbstring
          ini-file: development
          ini-values: memory_limit=2G

      - name: "Transform source code"
        shell: bash
        run: |
          composer install --no-interaction --no-progress --working-dir=compiler
          ./compiler/vendor/bin/simple-downgrade downgrade -c build/downgrade.php ${{ matrix.php-version }}
          composer dump

      - name: "Re-store PHP version"
        if: matrix.php-version == '7.4' || matrix.php-version == '8.0' || matrix.php-version == '8.1'
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ds,mbstring
          ini-file: development
          ini-values: memory_limit=2G

      - name: "Tests"
        run: "make tests"
